FLASK_APP=scratch.app:create_app
OPENAPI_VERSION = 3.0.2
OPENAPI_URL_PREFIX = /
OPENAPI_SWAGGER_UI_PATH = /swagger-ui
OPENAPI_SWAGGER_UI_URL = https://cdn.jsdelivr.net/npm/swagger-ui-dist/

SCRATCH_HEADER_TRACE=X-JETTY-TRACE-ID
SCRATCH_HEADER_REQUEST=X-JETTY-REQUEST-ID
SCRATCH_HEADER_ANONYMOUS=X-JETTY-ANONYMOUS-ID
